import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { GlobalContextCart } from "@/context/GlobalContext";
import Drawer from "@/components/Drawer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Food Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextCart>
          <Navbar />
          {children}
          {/* drawer carrito */}
          <Drawer />
        </GlobalContextCart>
      </body>
    </html>
  );
}
